---
openapi: 3.0.3
info:
  title: onecx-concessions v1 service
  version: 1.0.0
servers:
  - url: "http://onecx-concessions-svc:8080"
tags:
  - name: travelConcessionsV1
  - name: travelOfferingsV1
paths:
  /v1/travelOfferings{offeringId}:
    get:
      tags:
        - travelOfferingsV1
      description: search travelOfferings item by criteria
      operationId: searchTravelOfferingsItem
      parameters:
        - name: offeringId
          in: path
          required: true
          description: offering item ID
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TravelOffering'
        404:
          description: Travel Offering not found
components:
  schemas:
    TravelOffering:
      required:
        - itemId
      type: object
      properties:
        id:
          type: string
        state:
          type: string
        name:
          type: string
        allowedWagonClass:
          type: string
        requiredPayment:
          type: number 
        remoteId:
          type: string  
